### ISSUE TITLE
filter Sonar reported positions

### ISSUE THREAD

**Issue by xlinshan** [sofia819/ffxiv-map-link#1]
It keeps showing coordinates reported by Sonar, and the player name filter doesn't work for Sonar reports. Are there any way to ignore them?

**Comment by sofia819** [comment]
Hi! Yes, I can add a quick condition to ignore Sonar messages.

**Comment by sofia819** [comment]
In the new release, it should ignore messages sent by Sonar.

Let me know if you have other comments or questions, or feel free to close the issue. Thanks!
